name: CI  # Das ist der Workflow-Name – ändere zu etwas Passendem, z.B. "Test Simulation"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Ermöglicht manuellen Trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!  # Test-Befehl – ersetze später durch Python-Tests, z.B. python your_script.py
